development: &defaults
  domain: localhost
  reserved_subdomains: ['/demo\d*/', '/test\d*/', 'promo', '/app\d*/', '/assets\d*/', '/img\d*/', 'example']
  support_email: 'support@columbis.ru'
  support_phone: '8 800 555 43 77'
  session_key: _tourism_session
  secret_token: 7b50ff123f9a4d6f737cc6b079c4a886083a6d9bdef3137dbcf776e8fac7d1c406ce2842cff42ce045b2be05daa4fd3c1fc492fcc2de9388bf4b834dff642912
  delayed_job_user: user
  delayed_job_password: password
  public_controllers:
    - 'registrations'
    - 'sessions'
    - 'confirmations'
    - 'passwords'
    - 'devise/registrations'
    - 'devise/sessions'
    - 'devise/confirmations'
    - 'devise/passwords'
  total_entries: 10000
  per_page_list: [10,30,50]
  force_ssl: false
  ssl_options:
    hsts:
      subdomains: true

test:
  <<: *defaults
  domain: 127.0.0.1