development: &defaults
  domain: localhost
  session_key: _tourism_session
  secret_token: 7b50ff123f9a4d6f737cc6b079c4a886083a6d9bdef3137dbcf776e8fac7d1c406ce2842cff42ce045b2be05daa4fd3c1fc492fcc2de9388bf4b834dff642912
  delayed_job_user: user
  delayed_job_password: password
  public_controllers:
    - 'devise/sessions'
    - 'devise/passwords'
    - 'registrations'

test:
  <<: *defaults
  domain: 127.0.0.1