#!/usr/bin/env ruby
require 'yaml'

bazoved_path = '/opt/apps/tourism'
columbis_path = '/opt/apps/tourism-dev'

bazoved_dump = 'bazoved.db'
columbis_dump = 'columbis.db'

rvm_ruby_string = '2.0.0@tourism'

bazoved_env = 'production'
columbis_env = 'staging'

bazoved_db_config = YAML::load_file(File.join(bazoved_path, '/shared/config/database.yml'))[bazoved_env]
columbis_db_config = YAML::load_file(File.join(columbis_path, '/shared/config/database.yml'))[columbis_env]
columbis_tmp_db = columbis_db_config['database'] + '_tmp'

tables = %w(currency_courses delayed_jobs)
tables_dump = 'tables.data'

def secs(t)
  (Time.now - t).round(2)
end

t = Time.now
puts t

puts 'Save bazoved database'
system "export PGPASSWORD=#{bazoved_db_config["password"]} && pg_dump --host=#{bazoved_db_config["host"]} --port=#{bazoved_db_config["port"]} --username #{bazoved_db_config["username"]} --file #{columbis_path}/shared/#{bazoved_dump} -Fc #{bazoved_db_config["database"]}"
puts secs(t)

puts 'Drop temporary columbis database (to avoid errors with restore if it is)'
system "export PGPASSWORD=#{columbis_db_config["password"]} && dropdb -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} #{columbis_tmp_db} 2>/dev/null"
puts secs(t)

puts 'Create new temporary database for columbis'
system "export PGPASSWORD=#{columbis_db_config["password"]} && createdb -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} -T template0 #{columbis_tmp_db}"
puts secs(t)

puts 'Load data to temporary database for columbis'
system "export PGPASSWORD=#{columbis_db_config["password"]} && pg_restore -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} -d #{columbis_tmp_db} #{columbis_path}/shared/#{bazoved_dump}"
puts secs(t)

puts 'Migrate temporary columbis database'
system "/bin/bash -l -c 'rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && bundle exec rake db:migrate_to[#{columbis_tmp_db}] RAILS_ENV=#{columbis_env} 1>/dev/null'"
puts secs(t)

puts 'Save tables with special data for columbus to file'
system "export PGPASSWORD=#{columbis_db_config["password"]} && pg_dump -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} -f #{columbis_path}/shared/#{tables_dump} -Fc -a #{tables.map{|t| '-t ' + t}.join(' ')} #{columbis_db_config['database']}"
puts secs(t)

puts 'Save migrated columbis database'
system "export PGPASSWORD=#{columbis_db_config["password"]} && pg_dump --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} --username #{columbis_db_config["username"]} --file #{columbis_path}/shared/#{columbis_dump} -Fc #{columbis_tmp_db}"
puts secs(t)

puts 'Stop delayed_job process'
system "/bin/bash -l -c 'rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && RAILS_ENV=#{columbis_env} script/delayed_job stop 1>/dev/null'"
puts secs(t)

puts 'Stop sphinx process'
system "/bin/bash -l -c 'rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && bundle exec rake RAILS_ENV=#{columbis_env} thinking_sphinx:stop 1>/dev/null'"
puts secs(t)

puts 'Stop unicorn process'
system "if [ -e /opt/apps/tourism-dev/current/tmp/pids/unicorn.pid ]; then kill `cat /opt/apps/tourism-dev/current/tmp/pids/unicorn.pid`; fi"
puts secs(t)

puts 'Drop columbis database'
system "export PGPASSWORD=#{columbis_db_config["password"]} && dropdb -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} #{columbis_db_config["database"]}"
puts secs(t)

puts "Rename database #{columbis_tmp_db} to #{columbis_db_config['database']}"
system "export PGPASSWORD=#{columbis_db_config["password"]} && psql -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} -d #{bazoved_db_config["database"]} -c \"ALTER DATABASE #{columbis_tmp_db} RENAME TO #{columbis_db_config["database"]};\""
puts secs(t)

puts 'Restore tables with special data from dump'
system "export PGPASSWORD=#{columbis_db_config["password"]} && pg_restore -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} -d #{columbis_db_config['database']} -a #{columbis_path}/shared/#{tables_dump}"
puts secs(t)

# puts 'Create new columbis database'
# system "export PGPASSWORD=#{columbis_db_config["password"]} && createdb -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} -T template0 #{columbis_db_config["database"]}"
# puts secs(t)

# puts 'Load data to columbis database'
# system "export PGPASSWORD=#{columbis_db_config["password"]} && pg_restore -U #{columbis_db_config["username"]} --host=#{columbis_db_config["host"]} --port=#{columbis_db_config["port"]} -d #{columbis_db_config["database"]} #{columbis_path}/shared/#{columbis_dump}"
# puts secs(t)

# puts 'Migrate columbis database'
# system "rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && bundle exec rake db:migrate RAILS_ENV=#{columbis_env} 1>/dev/null"
# puts secs(t)

puts 'Start unicorn process'
system "/bin/bash -l -c 'rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && BUNDLE_GEMFILE=#{columbis_path}/current/Gemfile bundle exec unicorn -c #{columbis_path}/current/config/unicorn/#{columbis_env}.rb -E #{columbis_env} -D'"
puts secs(t)

puts 'Start sphinx process'
system "/bin/bash -l -c 'rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && bundle exec rake RAILS_ENV=#{columbis_env} thinking_sphinx:configure thinking_sphinx:index thinking_sphinx:start 1>/dev/null'"
puts secs(t)

puts 'Start delayed_job process'
system "/bin/bash -l -c 'rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && RAILS_ENV=#{columbis_env} script/delayed_job start 1>/dev/null'"
puts secs(t)

puts 'Copy upload files from bazoved to columbis'
system "cp -rf #{bazoved_path}/shared/uploads/* #{columbis_path}/shared/uploads"
puts secs(t)

puts 'Create specific users in columbis'
system "/bin/bash -l -c 'rvm use #{rvm_ruby_string} && cd #{columbis_path}/current && bundle exec rake RAILS_ENV=#{columbis_env} transfer:create_specific_users 1>/dev/null'"
puts secs(t)

puts "\n\n"